version: 0.2

env:
  secrets-manager:
    LOGIN: local/sonarqube:sonartoken
  variables:
    SONAR_HOST_URL: "https://sonarcloud.io"
    SONAR_PROJECT_KEY: "andriindocoder_monorepo-test_1"
    SONAR_ORG: "andriindocoder"

phases:
  install:
    commands:
      - which git || (echo "Git is not installed" && exit 1)
      - echo Install root dependencies...
      # - yarn install # Uncomment if there are any root dependencies to install
      - apt-get update
      - apt-get install -y jq
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - echo "Current path is >>> $(pwd)"
      - unzip sonar-scanner-cli-5.0.1.3006-linux.zip -d /opt
      - export PATH=$PATH:/opt/sonar-scanner-5.0.1.3006-linux/bin/
      - which sonar-scanner || (echo "SonarScanner not installed correctly" && exit 1)
      - git fetch --unshallow || git fetch --depth=1000

  pre_build:
    commands:
      - echo Change to the source directory...
      - cd $CODEBUILD_SRC_DIR
      - echo Making detect_changes.sh executable...
      - chmod +x detect_changes.sh
      - echo Checking for changes in the packages...
      - CHANGED_PROJECTS=$(./detect_changes.sh)

  build:
    commands:
      - echo "Building and analyzing changed packages..."
      - echo "CHANGED PROJECTS:" $CHANGED_PROJECTS
      - |
        function run_sonar_analysis {
          echo "Running SonarQube analysis for $1"
          sonar-scanner -Dsonar.login=$LOGIN -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.organization=$SONAR_ORG
          sleep 5
          curl "$SONAR_HOST_URL/api/qualitygates/project_status?projectKey=$SONAR_PROJECT_KEY" > result.json
          cat result.json
          if [ "$(jq -r '.projectStatus.status' result.json)" = "ERROR" ]; then
            echo "SonarQube analysis reported status as ERROR."
            exit 1
          fi
        }
        
        for PROJECT in $CHANGED_PROJECTS; do
          echo "Current Updated Project: $PROJECT"
          cd packages/$PROJECT
          run_sonar_analysis "$PROJECT"
          cd - # This takes you back to the previous directory (one level up)
        done

  post_build:
    commands:
      - echo Build and analysis completed for changed packages.
